import { test, expect, type Page } from '@playwright/test';
import { readFile } from 'node:fs/promises';
import type { Episode } from '../src/core/types';

type Fixture = Episode & { documents: (Episode['documents'][number] & { fixtureBytes?: number[] })[] };

async function readStoredFixture(page: Page) {
  return page.evaluate(async () => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('carethread-local', 1);
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
    try {
      const value = await new Promise<Fixture>((resolve, reject) => {
        const request = db.transaction('workspace').objectStore('workspace').get('episode');
        request.onsuccess = () => resolve(request.result);
        request.onerror = () => reject(request.error);
      });
      for (const doc of value.documents) {
        if (doc.blob) {
          doc.fixtureBytes = Array.from(new Uint8Array(await doc.blob.arrayBuffer()));
          delete doc.blob;
        }
      }
      return value;
    } finally { db.close(); }
  });
}

test('the previous release’s saved v1 episode reopens unchanged and retains sources after rapid edits', async ({ page }) => {
  // Captured from the frozen pre-refactor release, not regenerated by current code.
  const fixture: Fixture = JSON.parse(await readFile('tests/fixtures/workspace-v1.json', 'utf8'));
  await page.goto('/workspace');
  await expect(page.locator('.save-status')).toHaveText('Saved on this device');
  await page.evaluate(async saved => {
    const db = await new Promise<IDBDatabase>((resolve, reject) => {
      const request = indexedDB.open('carethread-local', 1);
      request.onsuccess = () => resolve(request.result);
      request.onerror = () => reject(request.error);
    });
    try {
      for (const doc of saved.documents) {
        if (doc.fixtureBytes) {
          doc.blob = new Blob([new Uint8Array(doc.fixtureBytes)], { type: doc.mime });
          delete doc.fixtureBytes;
        }
      }
      await new Promise<void>((resolve, reject) => {
        const transaction = db.transaction('workspace', 'readwrite');
        transaction.objectStore('workspace').put(saved, 'episode');
        transaction.oncomplete = () => resolve();
        transaction.onabort = () => reject(transaction.error);
        transaction.onerror = () => reject(transaction.error);
      });
    } finally { db.close(); }
  }, fixture);
  await page.reload();
  await expect(page.getByRole('heading', { name: 'A clearer view of your tests.' })).toBeVisible();
  await expect(page.locator('.save-status')).toHaveText('Saved on this device');
  expect(await readStoredFixture(page)).toEqual(fixture);

  const questions = () => page.getByRole('navigation', { name: 'Workspace', exact: true })
    .getByRole('button', { name: /Question sheet/ }).click();
  await questions();
  const field = page.getByLabel('Question about Culture');
  for (const text of ['First draft', 'Second draft', 'My latest clinic question']) await field.fill(text);
  await page.getByRole('link', { name: 'CareThread home', exact: true }).first().click();
  await page.getByRole('button', { name: 'Continue my workspace', exact: true }).first().click();
  await expect(page.locator('.save-status')).toHaveText('Saved on this device');
  await page.reload();
  await expect(page.getByRole('heading', { name: 'A clearer view of your tests.' })).toBeVisible();
  await questions();
  await expect(field).toHaveValue('My latest clinic question');
  const after = await readStoredFixture(page);
  expect(after.id).toBe(fixture.id);
  expect(after.schemaVersion).toBe(1);
  expect(after.documents).toEqual(fixture.documents);
  expect(after.revision).toBeGreaterThan(fixture.revision);
});
